### PR TITLE
Added Different Variations of Pi

### LINKED ISSUE #20: [FTU] - Add Pi
**Is your feature request related to a problem? Please describe.**

Nil.

**What is the feature request?**

Add Pi.

**Describe the solution you'd like**

Nil.

**Describe alternatives you've considered**

Nil.

**Additional context**

Nil.

### PR DESCRIPTION
**Pull request by CodeAsherPlayz**
Closes #20

### CODE REVIEW

**Review by rutvikpadhiyar000 — APPROVED** [review]
while its okay but i don't see need of multiple pi values approximated values are for simplicity only just using inbuilt pi value will be good.

**Comment by CodeAsherPlayz** [comment]
> while its okay but i don't see need of multiple pi values approximated values are for simplicity only just using inbuilt pi value will be good.

Just saying in Singpore they will use different pi values so we have to add more

**Comment by rutvikpadhiyar000** [comment]
Yeah we do that too but thats really because its difficult to calculate
with more accurate values if its done by computer than i dont see piont of
using appropriated values

**Comment by rutvikpadhiyar000** [comment]
But you are rigth sometimes it maybe given in question so it maybe usefull
to have option

**Pull request merged**
