### PR TITLE
More Functions

### PR DESCRIPTION
**Pull request by CodeAsherPlayz**

### CODE REVIEW

**Review by rutvikpadhiyar000 — COMMENTED** [review]
Hey number 6 is diameter of circle shouldn't it be 2*r

**Review by rutvikpadhiyar000 — CHANGES_REQUESTED** [review]
In triangle change base to side.
When there are only two conditions you can use ifand than else you don't need to check 2nd condition like in
Line 45 or 62

**Comment by CodeAsherPlayz** [comment]
Yes I saw haha, please review again

**Comment by rutvikpadhiyar000** [comment]
Change elif to else since else doesn't check condition it is faster than elif using it makes code more efficient.

**Comment by CodeAsherPlayz** [comment]
Okay :D

**Review by rutvikpadhiyar000 — APPROVED** [review]

**Comment by CodeAsherPlayz** [comment]
Thanks!

**Comment by rutvikpadhiyar000** [comment]
No problem

**Pull request merged**
