### PR TITLE
Created For Version 3.0

### PR DESCRIPTION
**Pull request by CodeAsherPlayz**
Also, can I have a few ideas for Version 3?

### CODE REVIEW

**Comment by rutvikpadhiyar000** [comment]
i don't have any idea currently but i was thinking of going out of shapes and add matrix and all.

**Review by rutvikpadhiyar000 — CHANGES_REQUESTED** [review]
while error handling is good i don't think that's a major update.
why not just add it to version 2 to make it minor update like 2.1

**Comment by CodeAsherPlayz** [comment]
No I was thinking of doing something for Version 3.0 so I copy and paste the code. This is actually for Version 3

**Review by rutvikpadhiyar000 — APPROVED** [review]

**Comment by CodeAsherPlayz** [comment]
> i don't have any idea currently but i was thinking of going out of shapes and add matrix and all.

Maybe we do for Angles?

**Comment by rutvikpadhiyar000** [comment]
ok you do angles and then i will do matrix

**Comment by CodeAsherPlayz** [comment]
okay

**Pull request merged**
